pipeline {
    agent any
    stages {
        stage('Newman Tests') {
            steps {
                sh '''
                node --version
                cd api/newman
                newman run techground_api_collection_christopher.postman_collection.json -e projectapi.postman_environment.json
                '''
            }
        }

        stage('Restassure Tests') {
            steps {
                sh '''
                cd api/newman
                newman run techground_api_collection_christopher.postman_collection.json -e projectapi.postman_environment.json
                '''
            }
        }

        stage('Jmeter Tests') {
            steps {
                sh '''
                cd api/rest-assure
                mvn clean test
                '''
            }
        }
    }
}