pipeline {
    agent any
    stages {
        stage('Newman Tests') {
            steps {
                sh '''
                cd api/newman
                newman run techground_api_collection_christopher.postman_collection.json -e projectapi.postman_environment.json
                '''
            }
        }

        stage('Rest Assured Tests') {
            steps {
                sh '''
                ls
                cd api
                ls
                cd rest-assured
                mvn clean test
                cd ..
                cd ..
                '''
            }
        }

        stage('Jmeter Tests') {
            steps {
                sh '''
                ls
                export PATH=/home/pjcalvov/jmeter/apache-jmeter-5.3/bin:$PATH
                cd load
                jmeter -n -t examen_load_test.jmx            
                '''
            }
        }
    }
}